version: '3.8'

services:
  # Servicio 1: El servidor Web con nuestro PHP y Apache
  web:
    build: .
    container_name: app_gestion_tareas
    ports:
      - "8080:80" # Mapea el puerto 8080 de tu PC al puerto 80 del contenedor
    volumes:
      - .:/var/www/html # Sincroniza tus archivos locales con el contenedor para ver cambios en vivo
    depends_on:
      - db # Espera a que la base de datos inicie antes de arrancar la web
    networks:
      - red-tareas

  # Servicio 2: El motor de base de datos MySQL
  db:
    image: mysql:8.0
    container_name: mysql_gestion_tareas
    ports:
      - "3307:3306" # Usamos el 3307 local por si ya tienes tu MySQL Workbench ocupando el 3306
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: gestion_tareas
    volumes:
      - db_data:/var/lib/mysql
      # Importa automáticamente tu script SQL al iniciar por primera vez
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    networks:
      - red-tareas

  # Servicio 3: El gestor de operaciones Jenkins
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins_gestion_tareas
    user: root # Da permisos para ejecutar acciones en el volumen
    ports:
      - "8085:8080" # Jenkins web en el puerto 8085 de tu PC
      - "50000:50000" # Puerto interno para agentes de Jenkins
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # Le presta el Docker de tu PC a Jenkins
    networks:
      - red-tareas

    # Servicio 4: El túnel de internet libre para el Webhook de GitHub
    # Servicio 4: El túnel de internet libre para el Webhook de GitHub
  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare_tunnel
    command: tunnel --url http://jenkins_gestion_tareas:8080
    restart: always
    networks:
      - red-tareas

volumes:
  db_data:
  jenkins_data: # Almacena de forma segura tus pipelines y configuraciones

networks:
  red-tareas:
    driver: bridge

